spring.application.name=Backend_Proiect_Colectiv
spring.data.mongodb.uri=mongodb+srv://<username>:<password>@cluster0.dptr5tx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=proiectcolectiv